name: Deploy To Production with Staging Check

on:
  push:
    branches:
    - master
  workflow_dispatch:

env:
  WEBAPP_NAME: agh-2024-webapp-1
  RESOURCE_GROUP: agh-2024-test-1
  SLOT_NAME: staging
  AZURE_WEBAPP_PACKAGE_PATH: './publish'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: false

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release

    - name: Run Unit Tests
      run: dotnet test ./tests/UnitTests/UnitTests.csproj --configuration Release

    - name: Run Functional Tests
      run: dotnet test ./tests/FunctionalTests/FunctionalTests.csproj --configuration Release

    - name: Publish Build Artifacts
      run: dotnet publish ./src/Web/Web.csproj -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/eShopOnWeb

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: eShopOnWeb
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/eShopOnWeb
    
  deploy-to-stage:
    name: Deploy to staging
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Staging'
      url: ${{ steps.deploy-to-stage.outputs.webapp-url }}
      
    steps:
    - name: Login to Azure
      uses: Azure/login@v2
      with:
        client-id: ${{ secrets.WEB_APP_CLIENT_ID }}
        tenant-id: ${{ secrets.WEB_APP_DIRECTORY_ID }}
        subscription-id: ${{ secrets.WEB_APP_SUBSCRIPTION_ID }} 
        enable-AzPSSession: true

    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: eShopOnWeb
    
    - name: Deploy to staging environment
      uses: azure/webapps-deploy@v3
      id: deploy-to-stage
      with: 
        app-name: ${{ env.WEBAPP_NAME }}
        slot-name:  ${{ env.SLOT_NAME }}
        package: '.'

  release-to-prod:
    name: Release to prod
    needs: deploy-to-stage
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: 'https://${{ env.WEBAPP_NAME }}.azurewebsites.net/'

    steps:
    - name: Login to Azure
      uses: Azure/login@v2
      with:
        client-id: ${{ secrets.WEB_APP_CLIENT_ID }}
        tenant-id: ${{ secrets.WEB_APP_DIRECTORY_ID }}
        subscription-id: ${{ secrets.WEB_APP_SUBSCRIPTION_ID }} 
        enable-AzPSSession: true

    - name: Swap slots
      run: az webapp deployment slot swap -s ${{ env.SLOT_NAME }} -n ${{ env.WEBAPP_NAME }} -g ${{ env.RESOURCE_GROUP }}
